@startuml
!pragma teoz true
skinparam monochrome true
skinparam defaultFontName Courier

title TransferDirectoryTree
mainframe **sd** TransferDirectoryTree

participant "fs:SenderFilesystem" as SenderFS
participant "bf:SenderBuffer" as SenderBF
participant "ps:Sender" as Sender
participant "ps:Recipient" as Recipient
' participant "fs:RecipientBuffer" as RecipientBF
' participant "fs:RecipientFilesystem" as RecipientFS

autonumber

legend bottom left
1.  Request to receive a directory tree rooted at <DIR_NAME>
3.  INSERT INTO cookie_table
        (id, expire_at, is_valid, next_path, ...)
        VALUES (<COOKIE>, <EXPIRE_DATETIME>, 0, <NEXT_PATH>, ...);
4.  Request to send a directory tree rooted at <DIR_NAME>
6.  Accept to receive the directory tree
7.  SELECT expire_at
        FROM cookie_table
        WHERE id = <COOKIE>;
10. Tell that the cookie in request has expired.
11. Tell that the request is faulty.
12. UPDATE cookie_table
        SET is_valid = 1
        WHERE id = <COOKIE>;
13. Tell "you may request back to get the next available node"
14. Get next node
15. SELECT expire_at, is_valid, next_path
        FROM cookie_table
        WHERE id = <COOKIE>;
' 18. UPDATE cookie_table
'         SET expire_at = <(current datetime)>,
'         WHERE id = <COOKIE>;
18. Tell that the cookie in request has expired.
19. UPDATE cookie_table
        SET expire_at = <(current datetime)>
        WHERE id = <COOKIE>;
20. Tell that the request is faulty.
21. Tell that the request is faulty.
26. UPDATE cookie_table
        SET expire_at = <(current datetime)>
        WHERE id = <COOKIE>;
27. Send node and Eng checksum, and tell "this is the last node."
31. UPDATE cookie_table
        SET next_path = <NEXT_PATH>
        WHERE id = <COOKIE>;
32. Send node and tell "there is at least one node left."
34. Refuse to receive the directory tree
35. UPDATE cookie_table
        SET expire_at = <(current datetime)>
        WHERE id = <COOKIE>;
' 36. Connection has been closed.
endlegend

activate Sender

' alt 0
alt Sender requests to send a directory tree

Sender -> Sender: Generate cookie

Sender ->> SenderBF: Put cookie record (remember cookie)
activate SenderBF
deactivate SenderBF

Sender -> Recipient: PUSH <DIR_NAME>\nCookie: <COOKIE>\nCookie-Expire: <EXPIRE_DATETIME>\n...

activate Recipient

Recipient -> Recipient: Remember cookie

' alt 0
else Recipient requests to receive a directory tree

Recipient -> Recipient: Generate cookie
Recipient -> Recipient: Remember cookie
Recipient -> Sender: PULL <PATH>\nCookie: <COOKIE>\nCookie-Expire: <EXPIRE_DATETIME>\n...

Sender ->> SenderBF: Put cookie record (remember cookie)
activate SenderBF
deactivate SenderBF

' alt 0
end

' alt 1
alt Recipient accepts to receive

' alt 1 alt 0
alt Sender requests to send a directory tree

Recipient -->> Sender: 1000 ACCEPTED\nCookie: <COOKIE>\n...

' alt 1 alt 0
else Recipient requests to receive a directory tree 

Sender -->> Recipient: 1000 ACCEPTED\nCookie: <COOKIE>\n...

' alt 1 alt 0
end


Sender -> SenderBF: Get cookie record
activate SenderBF
SenderBF -->> Sender: Cookie record
deactivate SenderBF

Sender -> Sender: Check cookie expiry

' break 0
break Faulty cookie

' break 0 alt 0
alt Cookie has expired

Sender ->> Recipient: 1002 COOKIE EXPIRED\n...

else Cookie does not exist

Sender ->> Recipient:  74 EBADMSG\n...

' break 0 alt 0
end

' break 0
end

Sender ->> SenderBF: Mark cookie record as valid
activate SenderBF
deactivate SenderBF

Sender ->> Recipient: POLL\nCookie: <COOKIE>\n...

' loop 0
loop

Recipient -> Sender: PICK <COOKIE>\nCookie: <COOKIE>\n...

Sender -> SenderBF: Get cookie record
activate SenderBF
SenderBF -->> Sender: Cookie record
deactivate SenderBF

Sender -> Sender: Check cookie expiry and validity

' break 1
break Faulty cookie

' break 1 alt 0
alt Cookie has expired

Sender ->> Recipient: 1002 COOKIE EXPIRED\n...

else Cookie is invalid

Sender ->> SenderBF: Expire out the cookie record (forget cookie)
activate SenderBF
deactivate SenderBF

Sender ->> Recipient: 74 EBADMSG\n...

else Cookie does not exist

Sender ->> Recipient:  74 EBADMSG\n...

' break 1 alt 0
end

' break 1
end

Sender -> SenderFS: Get node contents at path in cookie record
activate SenderFS
SenderFS -->> Sender: Node contents
deactivate SenderFS

Sender -> Sender: Determine next path
Sender -> Sender: Calculate Eng checksum

' break 2
break No nodes left

Sender ->> SenderBF: Expire out the cookie record (forget cookie)
activate SenderBF
deactivate SenderBF

Sender -->> Recipient: 2000 DONE\nCookie: <COOKIE>\nDigest: <ENG_DIGEST>\n...
Recipient -> Recipient: Forget cookie
Recipient -> Recipient: Calculate Chang checksum
Recipient -> Recipient: Compare Eng with Chang checksum

' break 2
end

Sender ->> SenderBF: Update cookie record's next path field
activate SenderBF
deactivate SenderBF

Sender -->> Recipient: 2001 MORE\nCookie: <COOKIE>\n...
Recipient -> Recipient: Calculate Chang checksum

' loop 0
end

' alt 1
else Recipient refuses to receive

' alt 1 alt 0
alt Sender requests to send a directory tree

Recipient -->> Sender: 1001 DECLINED\nCookie: <COOKIE>\n...

Sender ->> SenderBF: Expire out the cookie record (forget cookie)
activate SenderBF
deactivate SenderBF

' alt 1 alt 0
else Recipient requests to receive a directory tree 

Sender -->> Recipient: 1001 DECLINED\nCookie: <COOKIE>\n...
Recipient -> Recipient: Forget cookie

' alt 1 alt 0
end

'alt 0
end

' Sender ->> Recipient: 54 ECONNRESET\n...
' Recipient -> Recipient: Terminate

deactivate Recipient
deactivate Sender
@enduml
